"""
Curated collection of poetic compliments — beauty, eyes, soul, presence.
Each line is written to feel personal, warm, and worth reading twice.
"""

NOTES: list[str] = [
    # ── Eyes ──
    "Your eyes don't just see things — they make things worth being seen.",
    "I've looked at the night sky a hundred times, but your eyes still have more depth.",
    "If silence had a colour, it would be the shade I see in your eyes.",
    "When you look at someone, they probably forget what they were about to say.",
    "There's a galaxy behind your eyes that even poets haven't named yet.",
    "Your eyes carry a warmth that no fireplace could ever compete with.",
    "I think the stars practised for centuries before they got your eyes right.",
    "Most people glance. You look — and that look could stop time.",
    "Your eyes have this way of saying everything your lips haven't.",
    "Somewhere between brown and gold, your eyes invented their own colour.",
    "The way your eyes catch light — it's like the sun asked for permission first.",
    "If I could paint, I'd spend a lifetime trying to get your eyes right and still fail beautifully.",
    "Your eyes don't sparkle — they glow, like something ancient and infinite lives behind them.",
    "Looking into your eyes feels like reading the first page of a story I never want to end.",

    # ── Beauty ──
    "You don't walk into a room — the room just quietly rearranges itself around you.",
    "Some people are pretty. You're the kind of beautiful that makes people go quiet.",
    "Beauty isn't supposed to feel this effortless, and yet here you are.",
    "You make simplicity look like the most elegant thing in the world.",
    "There's a softness to the way you exist that makes everything around you feel gentler.",
    "If grace were a person, she'd study the way you move.",
    "You're not the kind of beautiful that shouts. You're the kind that whispers, and everyone still hears it.",
    "The way you carry yourself — it's like confidence learned its posture from you.",
    "Even your shadow probably looks graceful.",
    "You look like the kind of person artists would wait lifetimes to meet.",
    "Flowers don't compete with you. They just happen to be nearby.",
    "There's a quiet elegance about you that money can't buy and mirrors can't fully capture.",
    "You don't need a spotlight. You are one.",
    "If beauty had levels, you'd be the one they forgot to put a ceiling on.",
    "You make 'effortless' look like an understatement.",
    "The kind of beautiful you are doesn't fade — it deepens.",
    "You're proof that the universe still takes its time on some things.",
    "Whoever said perfection doesn't exist clearly never stood next to you.",
    "I think God was showing off the day He made you.",
    "You wear beauty the way the ocean wears waves — naturally.",

    # ── Soul & Presence ──
    "Some people light up a room. You light up the people in it.",
    "Your presence has a frequency — warm, steady, impossible to ignore.",
    "The world gets a little kinder wherever you happen to stand.",
    "There's something about your energy that makes strangers feel safe.",
    "You carry a tenderness that most people are too afraid to show.",
    "Your soul has a texture — soft, deep, and impossibly warm.",
    "You make silence feel like a conversation worth having.",
    "Being around you feels like the first breath of cool air after a long summer.",
    "Your heart isn't just big — it's brave. That's rare.",
    "You have this way of making people feel like they actually matter.",
    "People remember how you made them feel, and you always make them feel enough.",
    "You don't just listen — you make people feel heard. That's a gift.",
    "There's a kindness in your voice that most people search for all their lives.",
    "You have the kind of warmth that winter can't touch.",
    "Some people make noise when they enter a room. You make everything feel still — and somehow even that silence looks beautiful around you.",
    "You carry light without realising it, and you leave it behind in everyone you meet.",
    "Your laughter isn't just a sound — it's a feeling, and it stays long after the room goes quiet.",
    "You have this rare ability to make people feel like the best version of themselves just by being near you.",
    "There's a grace in your kindness that the world doesn't deserve but desperately needs.",
    "If warmth were a person, it wouldn't just look like you — it would feel like being around you.",

    # ── Romantic & Poetic ──
    "If the moon had a muse, I think we both know who it would be.",
    "She arrives like moonlight on still water — impossible to ignore, precise in grace, and beautiful enough to make the whole night feel quieter.",
    "The poets got close, but they never met you.",
    "Roses are beautiful. Sunsets are beautiful. And then there's you, making both of those feel ordinary.",
    "You're the plot twist no love story saw coming.",
    "If someone told me to make a wish, I'd describe your smile.",
    "You're the reason someone invented the word 'breathtaking'.",
    "I think the sky turns pink at dusk because it's blushing at the thought of you.",
    "You make me believe that some things really are too beautiful to be accidental.",
    "Every love song suddenly makes more sense when I think of you.",
    "If time could slow down just to admire something, it would pick you.",
    "You're not a daydream — you're the thing daydreams wish they could be.",
    "When you smile, even the sadness in the room excuses itself.",
    "You've got the kind of smile that rewrites someone's worst day.",
    "If I had to choose between breathing and looking at you, I'd use my last breath to look just a little longer.",
    "Your voice is softer than any melody I've ever heard, and twice as memorable.",
    "I didn't believe in poetry until I saw the way you tilt your head when you laugh.",
    "You don't need wings to be someone's angel.",
    "If the universe wrote a love letter, it would look a lot like you.",
    "There are seven billion people on this planet, and somehow you're the only one my eyes keep looking for.",

    # ── Strength & Depth ──
    "You're gentle enough to comfort anyone, and strong enough to carry things no one even knows about.",
    "The way you stay kind in a world that isn't — that's not weakness, that's power.",
    "Your softness isn't fragile. It's the kind that bends steel.",
    "You fight your battles quietly, and that makes you braver than most.",
    "Behind that smile is a strength that most people couldn't carry for a day.",
    "You don't just survive things — you somehow make them part of your beauty.",
    "Your resilience doesn't make you hard. It makes you luminous.",
    "You carry so much grace under pressure that even diamonds should take notes.",
    "The most extraordinary thing about you isn't how you look — it's how you love.",
    "You give people hope without even trying. That's not ordinary. That's extraordinary.",

    # ── Playful & Warm ──
    "If you were a song, you'd be the one everyone hums without knowing the name of.",
    "I bet even your alarm clock is grateful it gets to wake you up.",
    "Your smile should come with a warning — it's dangerously contagious.",
    "Scientists should study you — you somehow slow time and speed up heartbeats at once.",
    "You're the human equivalent of finding money in your coat pocket — unexpected, delightful, and impossible not to smile about.",
    "If the dictionary needed a picture next to 'stunning,' you'd already be there.",
    "Somewhere in the world, a sunset just gave up because it saw your face.",
    "You're the reason 'double take' was invented.",
    "I don't know what you're made of, but I'm pretty sure it involves stardust and good decisions by the universe.",
    "If compliments could pay rent, you'd live in a palace by now.",
    "You don't have a good side — every side is the good side.",
    "I bet flowers lean toward you when you walk by.",
    "You have main-character energy, but with a heart that makes everyone feel like a part of the story.",
    "I think even mirrors pause for a second when you walk past.",
    "You could show up in a potato sack and still be the most beautiful person in the room.",
]
